#!/usr/bin/env bash
# Version: 2024-04-15-01


# Interactive installation script for CLIProxyAPI
# Repository: https://github.com/router-for-me/CLIProxyAPI

set -e

# ---------- Helper Functions ----------
info() { echo -e "\033[1;34m[INFO]\033[0m $*"; }
error() { echo -e "\033[1;31m[ERROR]\033[0m $*" >&2; }

# Prompt for installation directory (default /opt/CLIProxyAPI)
read -rp "Enter installation directory [/opt/CLIProxyAPI]: " INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-/opt/CLIProxyAPI}

# Ensure the directory is absolute and writable
if [[ ! "$INSTALL_DIR" =~ ^/ ]]; then
  error "Installation directory must be an absolute path."
  exit 1
fi

# Detect if we need sudo for privileged locations
if [[ "$INSTALL_DIR" == /opt/* && $EUID -ne 0 ]]; then
  info "Installation directory requires root. Using sudo for privileged steps."
  SUDO='sudo'
else
  SUDO=''
fi

# ---------- Check Required Tools ----------
REQUIRED=(git python3 python3-venv)
for cmd in "${REQUIRED[@]}"; do
  if ! command -v $cmd >/dev/null 2>&1; then
    error "Required command '$cmd' not found. Installing..."
    $SUDO apt-get update -y && $SUDO apt-get install -y $cmd
  fi
done

# ---------- Clone or Update Repository ----------
if [[ -d "$INSTALL_DIR" ]]; then
  info "Directory $INSTALL_DIR already exists. Pulling latest changes."
  cd "$INSTALL_DIR"
  git pull origin main
else
  info "Cloning repository into $INSTALL_DIR"
  $SUDO git clone https://github.com/router-for-me/CLIProxyAPI "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ---------- Python Virtual Environment ----------
VENV_DIR="$INSTALL_DIR/.venv"
if [[ -d "$VENV_DIR" ]]; then
  info "Virtual environment already exists. Skipping creation."
else
  info "Creating Python virtual environment..."
  python3 -m venv "$VENV_DIR"
fi

# Activate venv and install requirements
source "$VENV_DIR/bin/activate"
if [[ -f "requirements.txt" ]]; then
  info "Installing Python dependencies..."
  pip install --upgrade pip setuptools
  pip install -r requirements.txt
else
  error "requirements.txt not found. Skipping pip install."
fi

# ---------- Configuration ----------
# Prompt for web login password and listening port
read -rp "Enter web interface password (default: admin): " WEB_PASS
WEB_PASS=${WEB_PASS:-admin}
read -rp "Enter listening port for API (default: 8000): " API_PORT
API_PORT=${API_PORT:-8000}

# Write configuration file (overwrite if exists)
cat > config.yaml <<EOF
# CLIProxyAPI configuration generated by interactive installer
router:
  host: 192.168.1.1
  username: admin
  password: $WEB_PASS

api:
  listen: 0.0.0.0:$API_PORT
  token: changeme
EOF
info "Configuration written to $INSTALL_DIR/config.yaml"

# ---------- Systemd Service ----------
read -rp "Install CLIProxyAPI as a systemd service? (y/N): " INSTALL_SERVICE
if [[ "$INSTALL_SERVICE" =~ ^[Yy]$ ]]; then
  SERVICE_FILE="/etc/systemd/system/cli-proxy-api.service"
  info "Creating systemd service at $SERVICE_FILE"
  $SUDO bash -c "cat > $SERVICE_FILE <<'EOF'
[Unit]
Description=CLIProxyAPI Service
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$INSTALL_DIR
ExecStart=$VENV_DIR/bin/python -m cli_proxy_api
Restart=on-failure
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
EOF"
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable cli-proxy-api.service
  $SUDO systemctl start cli-proxy-api.service
  info "Service installed and started. Use 'systemctl status cli-proxy-api' to check."
fi

# ---------- Post‑Installation Menu ----------
show_info() {
  echo "--- Installation Information ---"
  echo "Installation directory : $INSTALL_DIR"
  echo "Virtualenv           : $VENV_DIR"
  echo "Web password         : $WEB_PASS"
  echo "API listening port   : $API_PORT"
  if systemctl is-active --quiet cli-proxy-api.service; then
    echo "Systemd service      : installed & running"
  else
    echo "Systemd service      : not installed"
  fi
  echo "--------------------------------"
}

restart_service() {
  if [[ -f /etc/systemd/system/cli-proxy-api.service ]]; then
    $SUDO systemctl restart cli-proxy-api.service && info "Service restarted."
  else
    error "Service file not found. Cannot restart."
  fi
}

uninstall() {
  info "Uninstalling CLIProxyAPI..."
  # Stop and disable service if exists
  if [[ -f /etc/systemd/system/cli-proxy-api.service ]]; then
    $SUDO systemctl stop cli-proxy-api.service || true
    $SUDO systemctl disable cli-proxy-api.service || true
    $SUDO rm -f /etc/systemd/system/cli-proxy-api.service
    $SUDO systemctl daemon-reload
    info "Systemd service removed."
  fi
  # Remove installation directory
  $SUDO rm -rf "$INSTALL_DIR"
  info "Installation directory $INSTALL_DIR removed."
  exit 0
}

while true; do
  echo -e "\n--- CLIProxyAPI Management Menu ---"
  echo "1) Restart service"
  echo "2) Uninstall CLIProxyAPI"
  echo "3) Show installation info"
  echo "4) Exit"
  read -rp "Select an option [1-4]: " CHOICE
  case $CHOICE in
    1) restart_service ;;
    2) uninstall ;;
    3) show_info ;;
    4) echo "Good bye!"; break ;;
    *) echo "Invalid choice. Please pick 1-4." ;;
  esac
done

info "Installation script completed."
